spring: 
    profile:
        active:
        - dev
---
server:
    port:7001
    
spring:
    profile: dev
    application:    
        name: microservicecloud-config-eureka-client
        
eureka:
    instance:
        hostname: erueka7001.com
    client:
        register-witj-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/
---            
server:
    port:7001
    
spring:
    profile: test
    application:    
        name: microservicecloud-config-eureka-client
        
eureka:
    instance:
        hostname: erueka7001.com
    client:
        register-witj-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/